ORG 1000H
MANTISA DB 10000000B
EXP DB 00000000B

ORG 3000
; AJUSTA LA MANTISA LIKE A CHAMPION. RECIBE LOS PARAMETROS:
; AH = MANTISA
; AL = EXP
; DEVUELVE BL = 00H SI TODO SALIO JOYA, BL = FFH CASO CONTRARIO...
AJUSTAR: DEC AL
 JC NO_PUEDE ; SI DA CARRY ES PORQUE EXP ERA 0 Y NO PODIA DEC
 
 ; SI DECREMENTÉ EL EXP, DEBO MOVER LA MANTISA A LA IZQUIERDA
 ADD AH, AH
 JNC OK
 
 ; SI LLEGA ACA ES PORQUE: HUBO BORROW AL DEC EL EXP. O HUBO
 ; CARRY AL MOVER LA MANTISA
 NO_PUEDE: MOV BL, 0FFH
 JMP FIN
 
 ; SI LLEGA HASTA ACA ES PORQUE AL MOVER LA MANTISA NO HUBO CARRY
 OK: MOV BL, 000H
 FIN: RET

ORG 2000H
 ; PREPARO LOS PARAMETROS Y LLAMO A LA SUBRUTINA
 MOV AH, MANTISA
 MOV AL, EXP
 CALL AJUSTAR
HLT
END