ORG 1000H
NUM1A DW 3442
NUM1B DW 32
NUM2A DW 1222
NUM2B DW 23
BIEN DW ?
MAL DW ?
RESULT_A DW ?
RESULT_B DW ?

ORG 2000h
; SUMO PARTES BAJAS Y ALMACENO
MOV AX, NUM1A
ADD AX, NUM2A
MOV RESULT_A, AX

; SUMO PARTES ALTAS (TENIENDO EN CONSIDERACION EL CARRY)
MOV BX, NUM1B
ADC BX, NUM2B ; NOTESE QUE ACA USO ADC
MOV RESULT_B, BX

; SI DIO CARRY, SALIO "MAL"
JNC DIO_BIEN

; SI LLEGA A ESTA LINEA ES PORQUE DIO MAL
MOV MAL, 0FFH
JMP FIN

DIO_BIEN: MOV BIEN, 0FFH

FIN: hlt
END
